import { Course } from '@prisma/client';

export type Courses = Omit<Course, "id">

export const courses: Courses[] = [
    { name: 'Principles of Leadership', code: 'BCPC207', level: 'L300', semester: 'FIRST' },
    { name: 'Research Methods', code: 'BCPC301', level: 'L300', semester: 'FIRST' },
    { name: 'Programming', code: 'BITM301', level: 'L300', semester: 'FIRST' },
    { name: 'Database Management Systems II', code: 'BITM303', level: 'L300', semester: 'FIRST' },
    { name: 'Automation of Business Processes & Systems', code: 'BITM305', level: 'L300', semester: 'FIRST' },
    { name: 'Data Communication & Computer Networks', code: 'BITM307', level: 'L300', semester: 'FIRST' },
    { name: 'IT Sourcing and Procurement', code: 'BITM306', level: 'L300', semester: 'SECOND' },
    { name: 'Systems Analysis and Design', code: 'BITM304', level: 'L300', semester: 'SECOND' },
    { name: 'Management Information Systems', code: 'BITM302', level: 'L300', semester: 'SECOND' },
    { name: 'Business Ethics', code: 'BCPC212', level: 'L300', semester: 'SECOND' },
    { name: 'Global Dimention of Business', code: 'BCPC202', level: 'L300', semester: 'SECOND' },
    { name: 'Introduction to Environmental Management', code: 'BGEC104', level: 'L300', semester: 'SECOND' },
    { name: 'Internship', code: 'BCPC401', level: 'L400', semester: 'FIRST' },
    { name: 'Business Policy and Strategy', code: 'BCPC403', level: 'L400', semester: 'FIRST' },
    { name: 'Network and Systems Administration', code: 'BITM401', level: 'L400', semester: 'FIRST' },
    { name: 'IT Implementation and Maintanance', code: 'BITM403', level: 'L400', semester: 'FIRST' },
    { name: 'Systems Audit and Control', code: 'BITM405', level: 'L400', semester: 'FIRST' },
    { name: 'Management of IT Systems and Resources', code: 'BITM407', level: 'L400', semester: 'FIRST' },
    { name: 'Electronic Business', code: 'BITM409', level: 'L400', semester: 'FIRST' },
    { name: 'Professional Computing Practice', code: 'BITM402', level: 'L400', semester: 'SECOND' },
    { name: 'Information Management', code: 'BITM404', level: 'L400', semester: 'SECOND' },
    { name: 'Computer and Network Security', code: 'BITM406', level: 'L400', semester: 'SECOND' },
    { name: 'Software Quality Management', code: 'BITM408', level: 'L400', semester: 'SECOND' },
    { name: 'Mobile Web Development', code: 'BITM412', level: 'L400', semester: 'SECOND' },
    { name: 'Computer Networks', code: 'BITM201', level: 'L200', semester: 'FIRST' },
    { name: 'Information System', code: 'BCPC201', level: 'L200', semester: 'FIRST' },
    { name: 'Intro. to Business Finance', code: 'BCPC203', level: 'L200', semester: 'FIRST' },
    { name: 'Web Development Technologies', code: 'BITM203', level: 'L200', semester: 'FIRST' },
    { name: 'Elements of Marketing', code: 'BCPC205', level: 'L200', semester: 'FIRST' },
    { name: 'Legal Environment of Business', code: 'BCPC209', level: 'L200', semester: 'FIRST' },
    { name: 'Operating Systems', code: 'BITM202', level: 'L200', semester: 'SECOND' },
    { name: 'Database Management Systems I', code: 'BITM204', level: 'L200', semester: 'SECOND' },
    { name: 'Intro to Total Quality Management', code: 'BCPC206', level: 'L200', semester: 'SECOND' },
    { name: 'Quantitative Methods', code: 'BCPC208', level: 'L200', semester: 'SECOND' },
    { name: 'Principles of Economics', code: 'BCPC106', level: 'L200', semester: 'SECOND' },
    { name: 'Communication Skills', code: 'BGEC101', level: 'L100', semester: 'FIRST' },
    { name: 'Computer Graphics & Multimedia Applications', code: 'BITM101', level: 'L100', semester: 'FIRST' },
    { name: 'Logic & Critical Thinking', code: 'BGEC105', level: 'L100', semester: 'FIRST' },
    { name: 'Introduction to IT', code: 'BGEC107', level: 'L100', semester: 'FIRST' },
    { name: 'French Language', code: 'BGEC109', level: 'L100', semester: 'FIRST' },
    { name: 'Scholarly Writing', code: 'BGEC102', level: 'L100', semester: 'SECOND' },
    { name: 'Computer Hardware Systems', code: 'BITM102', level: 'L100', semester: 'SECOND' },
    { name: 'Programming Fundamentals', code: 'BITM104', level: 'L100', semester: 'SECOND' },
    { name: 'Introduction to Management', code: 'BCPC108', level: 'L100', semester: 'SECOND' },
    { name: 'Intro to Business Statistics', code: 'BCPC112', level: 'L100', semester: 'SECOND' },
    { name: 'Business French', code: 'BCAD108', level: 'L100', semester: 'SECOND' }
                    
                    
]